/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ExploreTalentRouteImport } from './routes/explore-talent'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIdRouteImport } from './routes/users.$id'
import { Route as PitchIdRouteImport } from './routes/pitch.$id'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPitchesNewRouteImport } from './routes/_authenticated/pitches.new'
import { Route as AuthenticatedPitchesIdWorkspaceRouteImport } from './routes/_authenticated/pitches.$id.workspace'
import { Route as AuthenticatedPitchesIdManageRouteImport } from './routes/_authenticated/pitches.$id.manage'
import { Route as AuthenticatedPitchesIdEditRouteImport } from './routes/_authenticated/pitches.$id.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTalentRoute = ExploreTalentRouteImport.update({
  id: '/explore-talent',
  path: '/explore-talent',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIdRoute = UsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PitchIdRoute = PitchIdRouteImport.update({
  id: '/pitch/$id',
  path: '/pitch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPitchesNewRoute = AuthenticatedPitchesNewRouteImport.update({
  id: '/pitches/new',
  path: '/pitches/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPitchesIdWorkspaceRoute =
  AuthenticatedPitchesIdWorkspaceRouteImport.update({
    id: '/pitches/$id/workspace',
    path: '/pitches/$id/workspace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPitchesIdManageRoute =
  AuthenticatedPitchesIdManageRouteImport.update({
    id: '/pitches/$id/manage',
    path: '/pitches/$id/manage',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPitchesIdEditRoute =
  AuthenticatedPitchesIdEditRouteImport.update({
    id: '/pitches/$id/edit',
    path: '/pitches/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/explore-talent': typeof ExploreTalentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/pitch/$id': typeof PitchIdRoute
  '/users/$id': typeof UsersIdRoute
  '/pitches/new': typeof AuthenticatedPitchesNewRoute
  '/pitches/$id/edit': typeof AuthenticatedPitchesIdEditRoute
  '/pitches/$id/manage': typeof AuthenticatedPitchesIdManageRoute
  '/pitches/$id/workspace': typeof AuthenticatedPitchesIdWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/explore-talent': typeof ExploreTalentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/pitch/$id': typeof PitchIdRoute
  '/users/$id': typeof UsersIdRoute
  '/pitches/new': typeof AuthenticatedPitchesNewRoute
  '/pitches/$id/edit': typeof AuthenticatedPitchesIdEditRoute
  '/pitches/$id/manage': typeof AuthenticatedPitchesIdManageRoute
  '/pitches/$id/workspace': typeof AuthenticatedPitchesIdWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/explore': typeof ExploreRoute
  '/explore-talent': typeof ExploreTalentRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/pitch/$id': typeof PitchIdRoute
  '/users/$id': typeof UsersIdRoute
  '/_authenticated/pitches/new': typeof AuthenticatedPitchesNewRoute
  '/_authenticated/pitches/$id/edit': typeof AuthenticatedPitchesIdEditRoute
  '/_authenticated/pitches/$id/manage': typeof AuthenticatedPitchesIdManageRoute
  '/_authenticated/pitches/$id/workspace': typeof AuthenticatedPitchesIdWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explore'
    | '/explore-talent'
    | '/sitemap.xml'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/saved'
    | '/pitch/$id'
    | '/users/$id'
    | '/pitches/new'
    | '/pitches/$id/edit'
    | '/pitches/$id/manage'
    | '/pitches/$id/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explore'
    | '/explore-talent'
    | '/sitemap.xml'
    | '/dashboard'
    | '/messages'
    | '/profile'
    | '/saved'
    | '/pitch/$id'
    | '/users/$id'
    | '/pitches/new'
    | '/pitches/$id/edit'
    | '/pitches/$id/manage'
    | '/pitches/$id/workspace'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/explore'
    | '/explore-talent'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/messages'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/pitch/$id'
    | '/users/$id'
    | '/_authenticated/pitches/new'
    | '/_authenticated/pitches/$id/edit'
    | '/_authenticated/pitches/$id/manage'
    | '/_authenticated/pitches/$id/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  ExploreTalentRoute: typeof ExploreTalentRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PitchIdRoute: typeof PitchIdRoute
  UsersIdRoute: typeof UsersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore-talent': {
      id: '/explore-talent'
      path: '/explore-talent'
      fullPath: '/explore-talent'
      preLoaderRoute: typeof ExploreTalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$id': {
      id: '/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof UsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pitch/$id': {
      id: '/pitch/$id'
      path: '/pitch/$id'
      fullPath: '/pitch/$id'
      preLoaderRoute: typeof PitchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitches/new': {
      id: '/_authenticated/pitches/new'
      path: '/pitches/new'
      fullPath: '/pitches/new'
      preLoaderRoute: typeof AuthenticatedPitchesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitches/$id/workspace': {
      id: '/_authenticated/pitches/$id/workspace'
      path: '/pitches/$id/workspace'
      fullPath: '/pitches/$id/workspace'
      preLoaderRoute: typeof AuthenticatedPitchesIdWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitches/$id/manage': {
      id: '/_authenticated/pitches/$id/manage'
      path: '/pitches/$id/manage'
      fullPath: '/pitches/$id/manage'
      preLoaderRoute: typeof AuthenticatedPitchesIdManageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pitches/$id/edit': {
      id: '/_authenticated/pitches/$id/edit'
      path: '/pitches/$id/edit'
      fullPath: '/pitches/$id/edit'
      preLoaderRoute: typeof AuthenticatedPitchesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedPitchesNewRoute: typeof AuthenticatedPitchesNewRoute
  AuthenticatedPitchesIdEditRoute: typeof AuthenticatedPitchesIdEditRoute
  AuthenticatedPitchesIdManageRoute: typeof AuthenticatedPitchesIdManageRoute
  AuthenticatedPitchesIdWorkspaceRoute: typeof AuthenticatedPitchesIdWorkspaceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedPitchesNewRoute: AuthenticatedPitchesNewRoute,
  AuthenticatedPitchesIdEditRoute: AuthenticatedPitchesIdEditRoute,
  AuthenticatedPitchesIdManageRoute: AuthenticatedPitchesIdManageRoute,
  AuthenticatedPitchesIdWorkspaceRoute: AuthenticatedPitchesIdWorkspaceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  ExploreTalentRoute: ExploreTalentRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PitchIdRoute: PitchIdRoute,
  UsersIdRoute: UsersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
